all:
	gcc -Wall -Wextra -Werror -c ft_display_programm.c
	gcc -Wall -Wextra -Werror ft_display_programm.o -o ft_display_programm

clean:
	rm -f ft_display_programm.o

fclean: clean
	rm -f ft_display_programm